edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true
normalize_comments = true
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
